export const environment = {
  ACCESS_KEY: 'ACCESS_KEY_PLACEHOLDER',
  SECRET_ACCESS_KEY: 'SECRET_ACCESS_KEY_PLACEHOLDER',
  BUCKET_REGION: 'BUCKET_REGION_PLACEHOLDER',
  BUCKET_NAME: 'BUCKET_NAME_PLACEHOLDER',
};
