name: CI Workflow

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace environment secrets
        run: |
          sed -i "s/ACCESS_KEY_PLACEHOLDER/${{ secrets.ACCESS_KEY }}/g" src/main/webapp/app/environment/environment.ts
          sed -i "s/SECRET_ACCESS_KEY_PLACEHOLDER/${{ secrets.SECRET_ACCESS_KEY }}/g" src/main/webapp/app/environment/environment.ts
          sed -i "s/BUCKET_REGION_PLACEHOLDER/${{ secrets.BUCKET_REGION }}/g" src/main/webapp/app/environment/environment.ts
          sed -i "s/BUCKET_NAME_PLACEHOLDER/${{ secrets.BUCKET_NAME }}/g" src/main/webapp/app/environment/environment.ts

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and run tests
        run: ./mvnw clean verify

      - name: Store Surefire reports
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/

  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace environment secrets
        run: |
          sed -i "s/ACCESS_KEY_PLACEHOLDER/${{ secrets.ACCESS_KEY }}/g" src/main/webapp/app/environment/environment.ts
          sed -i "s/SECRET_ACCESS_KEY_PLACEHOLDER/${{ secrets.SECRET_ACCESS_KEY }}/g" src/main/webapp/app/environment/environment.ts
          sed -i "s/BUCKET_REGION_PLACEHOLDER/${{ secrets.BUCKET_REGION }}/g" src/main/webapp/app/environment/environment.ts
          sed -i "s/BUCKET_NAME_PLACEHOLDER/${{ secrets.BUCKET_NAME }}/g" src/main/webapp/app/environment/environment.ts

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Generate coverage report
        run: ./mvnw verify

      - name: Upload Jacoco report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/

  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [test, coverage]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace environment secrets
        run: |
          sed -i "s/ACCESS_KEY_PLACEHOLDER/${{ secrets.ACCESS_KEY }}/g" src/main/webapp/app/environment/environment.ts
          sed -i "s/SECRET_ACCESS_KEY_PLACEHOLDER/${{ secrets.SECRET_ACCESS_KEY }}/g" src/main/webapp/app/environment/environment.ts
          sed -i "s/BUCKET_REGION_PLACEHOLDER/${{ secrets.BUCKET_REGION }}/g" src/main/webapp/app/environment/environment.ts
          sed -i "s/BUCKET_NAME_PLACEHOLDER/${{ secrets.BUCKET_NAME }}/g" src/main/webapp/app/environment/environment.ts

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build application
        run: ./mvnw clean package -Pprod -DskipTests

  skip_checks:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'test') || contains(github.ref, 'TEST') || contains(github.ref, 'tests')
    steps:
      - name: Skip checks on test branches
        run: echo "Skipping checks on test branches."

